Polish scraping
jannis-baum/weBlock pull request #17
Opened 2022-03-15 19:34 UTC by tiny-fish-T

2022-03-16 15:34 UTC, jannis-baum requested changes
please stop your linter from unnecessarily messing up formatting & undo these changes, makes it very hard to see what has actually changed.

would be cool if we could get some updates from the scraper while it's collecting the urls; running scraping with large `-n` currently still leads to very long wait times with no updates

2022-03-16 15:34 UTC, jannis-baum commented on server/scrape_negative
> +        urls = GoogleScraper.find_news_urls_for_query(query, args.narticles)
running `scrape_negative` with no arguments never terminates since it calls `GoogleScraper.find_news_urls_for_query(<query>, None)`

2022-03-16 15:34 UTC, jannis-baum commented on server/scrape_negative
> +            print("requesting url [{}]".format(url))
`print(f"requesting url {url}", end="\r")` to print all in same line

2022-03-16 15:34 UTC, jannis-baum commented on server/database/.mock-database.yaml
> +  topic: 'guardian: china human rights violation'
remove from vc

2022-03-17 09:01 UTC, jannis-baum requested changes

2022-03-17 09:01 UTC, jannis-baum commented on server/scrape_negative
> -        print("scraping for query [{}]".format(query))
this we can also move to the google scraper to avoid repeating the same line in `scrape_positive`

2022-03-17 09:59 UTC, jannis-baum commented on server/scrape_positive
> +        print(f"scraping for query [{query}]")
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 09:59 UTC, jannis-baum commented on server/scrape_negative
> -        print("scraping for query [{}]".format(query))
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 09:59 UTC, jannis-baum commented on server/scraper/article_scraper.py
> +        print("GoogleScraper: news urls extracted")
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 10:00 UTC, jannis-baum commented on server/scraper/article_scraper.py
>      def find_news_urls_for_query(query, n_articles=10, site=None):
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 10:00 UTC, jannis-baum commented on server/scrape_positive
> +        print(f"scraped {len(urls)} urls for query")
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 10:00 UTC, jannis-baum commented on server/scrape_negative
>      parser.add_argument("-n", "--narticles", type=int, action="store", default=0)
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 10:00 UTC, jannis-baum commented on server/.gitignore
> +.vscode
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 10:00 UTC, jannis-baum commented on .vscode/settings.json
> +}
fixed in [5262b14](https://github.com/jannis-baum/weBlock/pull/17/commits/5262b1474616134bc9ee959b4eb9c83d3159525f)

2022-03-17 10:00 UTC, jannis-baum approved these changes

2022-03-17 10:05 UTC, jannis-baum commented
[e4b8ae0](https://github.com/jannis-baum/weBlock/pull/17/commits/e4b8ae0acafa02dd7553f9c660af07bdb66554be) adds consistency with logging, see #23 for more detailed info on what could / should still be done.

2022-03-17 17:04 UTC, lucasliebe approved these changes
I can improve this PR, everything worked and also the code now seems nice and uniform enough to me. I like the changes but before merging please consider my comment made. I can`t test this case myself right now.

2022-03-17 17:49 UTC, jannis-baum commented on server/scrape-negative
> +    if len(NEGATIVE_QUERIES) == 0:
good point. we have to supply a default value of an empty list in `definitions.py`. i can do that tomorrow.

2022-03-18 08:55 UTC, merged